body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please provide as much detail as possible to help us give you the best answer.
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please be as specific as possible about what you're trying to understand or accomplish.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional information, code snippets, or screenshots that might help us understand your question better.
  - type: textarea
    id: attempted-solutions
    attributes:
      label: What have you tried so far?
      description: If applicable, describe any solutions or approaches you've already attempted.
  - type: dropdown
    id: urgency
    attributes:
      label: How urgent is this question?
      options:
        - Not urgent (just curious)
        - Somewhat urgent (blocking progress but not critical)
        - Very urgent (blocking critical work)
    validations:
      required: true
