body:
    - type: markdown
      attributes:
          value: |
              Thank you for getting in touch! Please fill out this form as completely as possible.

              Want to report a bug instead? [Use our bug report form](https://github.com/Neonsy/ScheduleOneInsights/issues/new?assignees=&labels=&template=bug-report.yml)
    - type: textarea
      id: describe-improvement
      attributes:
          label: Which Improvement Would You Like To Suggest?
          description: Please describe the specific improvement you are suggesting, and which existing functionality it relates to.
      validations:
          required: true
    - type: textarea
      id: reason-behind-it
      attributes:
          label: What Is the Reason Behind It?
          description: Explain what problem the enhancement is solving.
      validations:
          required: true
    - type: textarea
      id: proposed-implementation
      attributes:
          label: Proposed Implementation (Optional)
          description: If you have any ideas on how this feature could be implemented, please share them here.
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other relevant information.
